### ISSUE TITLE
Day2 by sagar

### ISSUE THREAD

**Issue by SagarSuryawan** [abhishek11125/Firstpost-News-Clone#8]

**Comment by SagarSuryawanshi-Dev** [comment]
make the same page the same as the previous page only change API data

- [x] create HTML of center content

- [x] create side content

- [x] fetch data

- [x] bottom side 

- [x] bottom ads



make the same page the same as the previous page only change API data

- [ ]create HTML of center content

- [x] create side content

- [x] fetch data

- [x] bottom side 

- [x] bottom ads


make the same page the same as the previous page only change API data

- [x] creat HTML of center content

- [x] creat side content

- [x] fetch data

- [x] bottom side 

- [x] bottom ads

**Comment by SagarSuryawanshi-Dev** [comment]
done
